# -------------------------------------------------------------
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# -------------------------------------------------------------

# Autogenerated By   : src/main/python/generator/generator.py
import unittest, contextlib, io


class TestOUTLIERBYISOLATIONFORESTAPPLY(unittest.TestCase):
    def test_outlierByIsolationForestApply(self):
        # Example test case provided in python the code block
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            import numpy as np
            from systemds.context import SystemDSContext
            from systemds.operator.algorithm import outlierByIsolationForest, outlierByIsolationForestApply
            with SystemDSContext() as sds:
                # Create training data
                np.random.seed(42)
                X_train = sds.from_numpy(np.random.randn(50, 2))

                # Train model
                model = outlierByIsolationForest(X_train, n_trees=10, subsampling_size=20, seed=7)

                # Create test data with one clear outlier
                X_test = sds.from_numpy(np.array([[0.1, 0.2], [10.0, 10.0]]))

                # Get anomaly scores
                scores = outlierByIsolationForestApply(model, X_test).compute()
                print(f"Normal point score: {scores[0, 0]:.3f}")
                print(f"Outlier score: {scores[1, 0]:.3f}")

            expected = """Normal point score: 0.435
Outlier score: 0.623"""
        self.assertEqual(buf.getvalue().strip(), expected)


if __name__ == '__main__':
    unittest.main()
