# -------------------------------------------------------------
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# -------------------------------------------------------------

# Autogenerated By   : src/main/python/generator/generator.py
# Autogenerated From : scripts/builtin/outlierByIsolationForestApply.dml

from typing import Dict, Iterable

from systemds.operator import OperationNode, Matrix, Frame, List, MultiReturn, Scalar
from systemds.utils.consts import VALID_INPUT_TYPES


def outlierByIsolationForestApply(iForestModel: List,
                                  X: Matrix):
    """
     Builtin function that calculates the anomaly score as described in [Liu2008]
     for a set of samples `X` based on an iForest model.
    
     [Liu2008]:
       Liu, F. T., Ting, K. M., & Zhou, Z. H.
       (2008, December).
       Isolation forest.
       In 2008 eighth ieee international conference on data mining (pp. 413-422).
       IEEE.
    
     .. code-block:: python
    
       >>> import numpy as np
       >>> from systemds.context import SystemDSContext
       >>> from systemds.operator.algorithm import outlierByIsolationForest, outlierByIsolationForestApply
       >>> with SystemDSContext() as sds:
       ...     # Create training data
       ...     np.random.seed(42)
       ...     X_train = sds.from_numpy(np.random.randn(50, 2))
       ...
       ...     # Train model
       ...     model = outlierByIsolationForest(X_train, n_trees=10, subsampling_size=20, seed=7)
       ...
       ...     # Create test data with one clear outlier
       ...     X_test = sds.from_numpy(np.array([[0.1, 0.2], [10.0, 10.0]]))
       ...
       ...     # Get anomaly scores
       ...     scores = outlierByIsolationForestApply(model, X_test).compute()
       ...     print(f"Normal point score: {scores[0, 0]:.3f}")
       ...     print(f"Outlier score: {scores[1, 0]:.3f}")
       Normal point score: 0.435
       Outlier score: 0.623
    
    
    
    
    :param iForestModel: The trained iForest model as returned by outlierByIsolationForest
    :param X: Samples to calculate the anomaly score for
    :return: Column vector of anomaly scores corresponding to the samples in X.
        Samples with an anomaly score > 0.5 are generally considered to be outliers
    """

    params_dict = {'iForestModel': iForestModel, 'X': X}
    return Matrix(iForestModel.sds_context,
        'outlierByIsolationForestApply',
        named_input_nodes=params_dict)
